- name: restart_docker
  become: true
  service:
    name: docker
    state: restarted

#- name: Restart machine
#  become: true
#  become_method: sudo
#  shell: sleep 5 && shutdown -r now "Reboot triggered by Ansible script"
#  async: 1
#  poll: 0
#  ignore_errors: true


#- name: reboot
#  reboot:
